In [1]:
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.cluster import KMeans
from sklearn import metrics, tree
from pickle import dump

# Lectura

In [2]:
df = pd.read_csv("../../data/interim/types_of_pc.csv", sep="|")

In [3]:
df

CPU  CPU_GEN CPU_SERIE  RAM   GPU  GPU_TI    HDD   SSD     TARGET
0          3        5         Q    2    -1       0    500     0  Ofimatica
1          3        5         Q    2    -1       0    500   128  Ofimatica
2          3        5         Q    2    -1       0    500   256  Ofimatica
3          3        5         Q    2    -1       0    750     0  Ofimatica
4          3        5         Q    2    -1       0    750   128  Ofimatica
...      ...      ...       ...  ...   ...     ...    ...   ...        ...
1097644    7       11         Z  124  3080       1   9216  2048     Diseño
1097645    7       11         Z  124  3080       1   9216  4096     Diseño
1097646    7       11         Z  124  3080       1  10240  1024     Diseño
1097647    7       11         Z  124  3080       1  10240  2048     Diseño
1097648    7       11         Z  124  3080       1  10240  4096     Diseño

[1097649 rows x 9 columns]

# Preporcesamiento

In [4]:
cpu_label_encoder = preprocessing.LabelEncoder()
cpu_label_encoder.fit(df["CPU_SERIE"])
dump(cpu_label_encoder, open('/work/games_seeker/models/cpu_serie_encoder.pkl', 'wb'))
encoder_cpu_serie = cpu_label_encoder.transform(df["CPU_SERIE"])

In [5]:
target_label_encoder = preprocessing.LabelEncoder()
target_label_encoder.fit(df["TARGET"])
dump(target_label_encoder, open('/work/games_seeker/models/target_encoder.pkl', 'wb'))
encoder_target = target_label_encoder.transform(df["TARGET"])

In [6]:
df["CPU_SERIE"] = encoder_cpu_serie
df["TARGET"] = encoder_target

In [7]:
target_label_encoder.transform(["Gamer", "Ofimatica", "Diseño"])

array([1, 2, 0])

In [8]:
df

CPU  CPU_GEN  CPU_SERIE  RAM   GPU  GPU_TI    HDD   SSD  TARGET
0          3        5          2    2    -1       0    500     0       2
1          3        5          2    2    -1       0    500   128       2
2          3        5          2    2    -1       0    500   256       2
3          3        5          2    2    -1       0    750     0       2
4          3        5          2    2    -1       0    750   128       2
...      ...      ...        ...  ...   ...     ...    ...   ...     ...
1097644    7       11          4  124  3080       1   9216  2048       0
1097645    7       11          4  124  3080       1   9216  4096       0
1097646    7       11          4  124  3080       1  10240  1024       0
1097647    7       11          4  124  3080       1  10240  2048       0
1097648    7       11          4  124  3080       1  10240  4096       0

[1097649 rows x 9 columns]

In [9]:
df.to_csv("../../data/processed/types_of_pc.csv", sep = "|")

In [10]:
X_COLUMNS = ['CPU', 'CPU_GEN', 'CPU_SERIE', 'RAM', 'GPU', 'GPU_TI', 'HDD', 'SSD']
Y_COLUMN = ["TARGET"]

In [11]:
x = df[X_COLUMNS].values
x

array([[    3,     5,     2, ...,     0,   500,     0],
       [    3,     5,     2, ...,     0,   500,   128],
       [    3,     5,     2, ...,     0,   500,   256],
       ...,
       [    7,    11,     4, ...,     1, 10240,  1024],
       [    7,    11,     4, ...,     1, 10240,  2048],
       [    7,    11,     4, ...,     1, 10240,  4096]])

In [12]:
y = df[Y_COLUMN]
y

TARGET
0             2
1             2
2             2
3             2
4             2
...         ...
1097644       0
1097645       0
1097646       0
1097647       0
1097648       0

[1097649 rows x 1 columns]

In [13]:
y = [i[0] for i in y.values]

# Modelo inicial

In [14]:
kmeans_model = KMeans(n_clusters=3)

In [15]:
kmeans_model.fit(x)

KMeans(n_clusters=3)

In [16]:
y_kmeans = kmeans_model.predict(x)

In [17]:
accuracy = metrics.adjusted_rand_score(y, y_kmeans)

# Otros modelos

In [18]:
tree_model = tree.DecisionTreeClassifier()

In [19]:
tree_model = tree_model.fit(x, y)

In [20]:
tree_model.score(x, y)

0.9827813809332492

In [21]:
tree_model.predict([[5, 11, 1, 32, 1050, 1, 2048, 2048]])

array([0])

In [22]:
dump(tree_model, open('/work/games_seeker/models/model.pkl', 'wb'))

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=07e29549-6cbf-4e88-b69c-0fc48f2d6023' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>